sudo: required
services:
    - docker
    
 before_install:
    - docker build -t elenivl/react-test -f ./client/Dockerfile.dev ./client

script:
    -  docker run CI=true eleinivl/react-test npm test -- --coverage

after_success:
    - docker build -t elenivl/multi-client ./client
    - docker build -t elenivl/multi-nginx ./nginx
    - docker build -t elenivl/multi-server ./server
    - docker build -t elenivl/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push elenivl/multi-client
    - docker push elenivl/multi-nginx   
    - docker push elenivl/multi-server
    - docker push elenivl/multi-worker